[package]
name = "tcprs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tun-tap = "0.1.3"
etherparse = "0.12.0"
mpstthree = "0.1.16"

[dev-dependencies]
crossbeam-channel = "0.5.6"

