[package]
name = "mpstrust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.5.6"
tun-tap = "0.1.3"
etherparse = "0.13.0"
smoltcp = "0.9.1"
pnet = "0.33.0"
